# Generated by Django 4.2.3 on 2023-07-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="price",
            field=models.IntegerField(default=10),
        ),
    ]
